# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\elugo\Documents\GitHub\Full_Stack_Programming_for_Complete_Beginners_in_Python\GUI\project\design\dialog_delete_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_delete(object):
    def setupUi(self, dialog_delete):
        dialog_delete.setObjectName("dialog_delete")
        dialog_delete.resize(329, 114)
        self.button_box = QtWidgets.QDialogButtonBox(dialog_delete)
        self.button_box.setGeometry(QtCore.QRect(10, 80, 311, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_box.setFont(font)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.txt_delete_notice = QtWidgets.QTextBrowser(dialog_delete)
        self.txt_delete_notice.setGeometry(QtCore.QRect(11, 11, 311, 41))
        self.txt_delete_notice.setObjectName("txt_delete_notice")

        self.retranslateUi(dialog_delete)
        self.button_box.accepted.connect(dialog_delete.accept)
        self.button_box.rejected.connect(dialog_delete.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog_delete)

    def retranslateUi(self, dialog_delete):
        _translate = QtCore.QCoreApplication.translate
        dialog_delete.setWindowTitle(_translate("dialog_delete", "Delete book"))
        self.txt_delete_notice.setHtml(_translate("dialog_delete", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">Are you sure you want to delete this book?</span></p></body></html>"))
